### ISSUE TITLE
3일차 Todo 

### ISSUE THREAD

**Issue by WhiteCapella** [DE32megabox/airflow#21]
- [ ] Transform 모듈 완성
-- Repository Transform : Release/d3.0.0 배포
--- Release Note : Release/d3.0.0 작성
--- Repository Transform : README.md 수정

- [ ] Repository Airflow : transform dev
-- transform dags 개발
--- dags/transform_q1.py // dev/d3.0.1
--- dags/transform_q2.py // dev/d3.0.2
--- dags/transform_q3.py // dev/d3.0.3
--- merge dev/d3.0.0 transforms

- [ ] Load 모듈 완성
-- Repository Load : Release/d3.0.0 배포
--- Release Note : Release/d3.0.0 작성
--- Repository Load : README.md 수정

- [ ] Repository Airflow : load dev
-- load dags 개발
--- dags/load_q1.py // dev/d3.0.1
--- dags/load_q2.py // dev/d3.0.2
--- dags/load_q3.py // dev/d3.0.3
--- merge dev/d3.0.0 loads

- [ ] Airflow 모듈 Release
-- Repository Airflow : Release/d3.0.0 배포
--- Release Note : Release/d3.0.0 작성
--- Repository Airflow : README.md 수정

- [ ] 최종 Test
- [ ] 발표자료 제작
- [ ] 회고록 작성
